### PR TITLE
Fixed login flow

### PR DESCRIPTION
**Pull request by gzalo**
Fixes login issues (errors.com.epicgames.accountportal.session_invalidated)

Ported from https://github.com/Terbau/fortnitepy/commit/691102a66e359bf4a3f2bc7526b68d8157ad1711

### CODE REVIEW

**Comment by TimVerheul** [comment]
Fixed in next commit.
Thank you for the PR!

**Comment by gzalo** [comment]
Thanks! There is also a thing that prevents the API from working: the V1 endpoints are no longer online, so the library would probably have to be rewriten to use the other one (which supports waay more stats fields, apparently)

**Comment by TimVerheul** [comment]
I noticed that and i'm working on it plus supporting multiple auth flows. I often get a captcha error so that needs to be fixed. Do you have a list of the updated V2 endpoints @gzalo ?

**Comment by gzalo** [comment]
Awesome! The main one seems to be https://statsproxy-public-service-live.ol.epicgames.com/statsproxy/api/statsv2/account/ Not sure about the other ones

**Comment by TimVerheul** [comment]
fixed in latest commit.

**Pull request closed without merging**
